# Ejercicios Dos

In [10]:
import numpy as np
import math

## Ejercicio 1:

In [11]:
A=np.array([[1,4],[-1,3],[2,-9]])
cero=np.zeros((3,2))
print("A".center(20,'-'))
print(A)
print("Ceros".center(20,'-'))
print(cero)

---------A----------
[[ 1  4]
 [-1  3]
 [ 2 -9]]
-------Ceros--------
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
print("A + 0 = A".center(20,'-'))
print(A + cero)
print("A - 0 = A".center(20,'-'))
print(A - cero)
print("A - A = 0".center(20,'-'))
print(A - A)

-----A + 0 = A------
[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]
-----A - 0 = A------
[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]
-----A - A = 0------
[[0 0]
 [0 0]
 [0 0]]


## Ejercicio 2:

In [21]:
A2=np.array([[3,0],[-1,5]])
B=np.array([[4,-2,1],[0,2,3]])
print("A".center(20,'-'))
print(A2)
print("B".center(20,'-'))
print(B)

---------A----------
[[ 3  0]
 [-1  5]]
---------B----------
[[ 4 -2  1]
 [ 0  2  3]]


In [25]:
print("3B".center(20,'-'))
print(3*B)
print("Dado que las matrices son de diferente dimesion, solo se puede realizar la multiplicacion de '3B'")
print("A + 3B".center(20,'-'))
print(A2 + 3*B)

---------3B---------
[[12 -6  3]
 [ 0  6  9]]
Dado que las matrices son de diferente dimesion, solo se puede realizar la multiplicacion de '3B'
-------A + 3B-------


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [34]:
print("AB".center(20,'-'))
print(A2@B)
print("A^3".center(20,'-'))
print(np.linalg.matrix_power(A2,3))
print("B^2".center(20,'-'))
print("La matriz de B no se puede elevar por que no es cuadrada")
print(np.linalg.matrix_power(B,2))    


---------AB---------
[[12 -6  3]
 [-4 12 14]]
--------A^3---------
[[ 27   0]
 [-49 125]]
--------B^2---------
La matriz de B no se puede elevar por que no es cuadrada


LinAlgError: Last 2 dimensions of the array must be square

In [36]:
print("(5A)B".center(20,'-'))
print((5*A2)@B)

-------(5A)B--------
[[ 60 -30  15]
 [-20  60  70]]


## Ejercicio 3:

In [43]:
restaurantes = np.array([[30,15,4],[25,18,8]])
tiendas = np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print("Tiendas".center(40,'-'))
print(tiendas.T)
costo_por_tienda = restaurantes@tiendas.T
print("Costo Tienda 1".center(40,'-'))
print(costo_por_tienda[0,0]+costo_por_tienda[1,0])
print("Costo Tienda 2".center(40,'-'))
print(costo_por_tienda[0,1]+costo_por_tienda[1,1])

----------------Tiendas-----------------
[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
-------------Costo Tienda 1-------------
192.6
-------------Costo Tienda 2-------------
196.0


## Ejercicio 4:

In [67]:
productos=np.array([[200,75],[150,100],[100,125]]).T
print("Productos".center(20,'-'))
print(productos)
embarques=np.array([[1.50,1.75],[1,1.50],[2,1]])
print("Embarques".center(20,'-'))
print(embarques)
print("Matriz de costos".center(20,'-'))
costos=productos@embarques
print(costos)
print("-".center(30,'-'))
print(f"Almacen 1: \n Camion: ${costos[0,0]} \n Tren: ${costos[1,0]} \n Total: ${costos[0,0]+costos[1,0]}")
print("-".center(30,'-'))
print(f"Almacen 2: \n Camion: ${costos[0,1]} \n Tren: ${costos[1,1]} \n Total: ${costos[0,1]+costos[1,1]}")
camion = costos[0,0]+costos[1,0]
tren = costos[0,1]+costos[1,1]
print("-".center(30,'-'))
if camion > tren:
    print("Sale mas rentable por tren")
else:
    print("Sale mas rentable por camion")

-----Productos------
[[200 150 100]
 [ 75 100 125]]
-----Embarques------
[[1.5  1.75]
 [1.   1.5 ]
 [2.   1.  ]]
--Matriz de costos--
[[650.   675.  ]
 [462.5  406.25]]
------------------------------
Almacen 1: 
 Camion: $650.0 
 Tren: $462.5 
 Total: $1112.5
------------------------------
Almacen 2: 
 Camion: $675.0 
 Tren: $406.25 
 Total: $1081.25
------------------------------
Sale mas rentable por tren


## Ejercicio 5

In [71]:
print("Sistema 1".center(40,'-'))
eq0=np.array([[3,2],[6,4]])
print("Ecuaciones".center(20,'-'))
print(eq0)
ind0=np.array([6,-9])
print("Independientes".center(20,'-'))
print(ind0)
print("Solucion".center(20,'-'))
print("No se encuentra una solucion ya que las rectas son paralelas")
print(np.linalg.solve(eq0,ind0))

---------------Sistema 1----------------
-----Ecuaciones-----
[[3 2]
 [6 4]]
---Independientes---
[ 6 -9]
------Solucion------
No se encuentra una solucion ya que las rectas son paralelas


LinAlgError: Singular matrix

In [81]:
print("Sistema 2".center(40,'-'))
eq1=np.array([[1,1],[1,-4]])
print("Ecuaciones".center(20,'-'))
print(eq1)
ind1=np.array([3,1])
print("Independientes".center(20,'-'))
print(ind1)
print("Solucion".center(20,'-'))
sol1=np.linalg.solve(eq1,ind1)
print(sol1)
print(f"x= {sol1[0]}\t y= {sol1[1]}")

print("Sistema 3".center(40,'-'))
eq2=np.array([[2,-1,2],[2,3,-1],[1,2,2]])
print("Ecuaciones".center(20,'-'))
print(eq2)
ind2=np.array([3,0,-12])
print("Independientes".center(20,'-'))
print(ind2)
print("Solucion".center(20,'-'))
sol2=np.linalg.solve(eq2,ind2)
print(sol2)
print(f"x= {sol2[0]}\t y= {sol2[1]} \t z={sol2[2]}")

---------------Sistema 2----------------
-----Ecuaciones-----
[[ 1  1]
 [ 1 -4]]
---Independientes---
[3 1]
------Solucion------
[2.6 0.4]
x= 2.6	 y= 0.4
---------------Sistema 3----------------
-----Ecuaciones-----
[[ 2 -1  2]
 [ 2  3 -1]
 [ 1  2  2]]
---Independientes---
[  3   0 -12]
------Solucion------
[ 3.65217391 -3.7826087  -4.04347826]
x= 3.6521739130434785	 y= -3.782608695652174 	 z=-4.043478260869565
